[project]
name = "pybtex-apa7-style"
version = "0.1.5"
description = "Provides APA7 style for Pybtex"
readme = "README.md"
authors = [
    { name = "Chris Proctor", email = "github.com@accounts.chrisproctor.net" },
]
license = "MIT"
requires-python = ">=3.9"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Topic :: Text Processing :: Markup",
    "Topic :: Utilities",
]
dependencies = [
    "pybtex>=0,<1",
]

[project.urls]
Homepage = "https://github.com/cproctor/pybtex-apa7-style"
Repository = "https://github.com/cproctor/pybtex-apa7-style"

[project.entry-points."pybtex.style.formatting"]
apa7 = "formatting.apa:APAStyle"

[project.entry-points."pybtex.style.labels"]
apa7 = "labels.apa:LabelStyle"

[project.entry-points."pybtex.style.names"]
firstlast = "names.firstlast:NameStyle"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["formatting", "labels", "names"]
